import mock from './mock'
import './auth'

mock.onAny().reply(config => {
  if (config && config.url && config.url.includes('/count')) {
    return [
      200,
      {
        statusCode: 200,
        data: {
          users: 150,
          business: 45,
          agents: 12,
          Invoices: 32,
          payments: 28,
          disputes: 4,
          checkouts: 19,
        },
      },
    ]
  }

  const staticItems = [
    {
      _id: '1',
      id: '1',
      uuid: 'uuid-1',
      name: 'John Doe',
      firstName: 'John',
      lastName: 'Doe',
      email: 'john@example.com',
      phone: '+1234567890',
      businessName: 'Acme Corp',
      companyType: 'LLC',
      industry: 'Technology',
      amount: 1500.0,
      currency: { code: 'USD', symbol: '$' },
      transactionId: 'TXN-1001',
      type: 'payment',
      planName: 'Premium',
      interval: 'month',
      price: 99.99,
      status: 'active',
      isEmailVerified: true,
      isPhoneVerified: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      _id: '2',
      id: '2',
      uuid: 'uuid-2',
      name: 'Jane Smith',
      firstName: 'Jane',
      lastName: 'Smith',
      email: 'jane@example.com',
      phone: '+1987654321',
      businessName: 'Globex Inc',
      companyType: 'Corporation',
      industry: 'Retail',
      amount: 250.5,
      currency: { code: 'USD', symbol: '$' },
      transactionId: 'TXN-1002',
      type: 'refund',
      planName: 'Starter',
      interval: 'year',
      price: 199.99,
      status: 'pending',
      isEmailVerified: false,
      isPhoneVerified: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      _id: '3',
      id: '3',
      uuid: 'uuid-3',
      name: 'Bob Johnson',
      firstName: 'Bob',
      lastName: 'Johnson',
      email: 'bob@example.com',
      phone: '+1555123456',
      businessName: 'Initech',
      companyType: 'Sole Proprietorship',
      industry: 'Software',
      amount: 4500.0,
      currency: { code: 'USD', symbol: '$' },
      transactionId: 'TXN-1003',
      type: 'transfer',
      planName: 'Enterprise',
      interval: 'month',
      price: 499.99,
      status: 'inactive',
      isEmailVerified: true,
      isPhoneVerified: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ]

  const userStaticStats = {
    total: 8430,
    yesterday: 50,
    thisWeek: 120,
    lastWeek: 90,
    thisMonth: 400,
    lastMonth: 350,
  }
  const bizStaticStats = {
    total: 450,
    yesterday: 5,
    thisWeek: 12,
    lastWeek: 9,
    thisMonth: 40,
    lastMonth: 35,
  }

  return [
    200,
    {
      statusCode: 200,
      status: 200,
      success: true,
      message: 'Success',
      walletCount: 2541,
      virtualDebitCards: 1205,
      physicalDebitCards: 840,
      walletBalance: 145000.5,
      stripeIssuingBalance: 42500.0,
      usersStats: userStaticStats,
      businessesStats: bizStaticStats,
      data: {
        walletCount: 2541,
        virtualDebitCards: 1205,
        physicalDebitCards: 840,
        walletBalance: 145000.5,
        stripeIssuingBalance: 42500.0,
        usersStats: userStaticStats,
        businessesStats: bizStaticStats,
        items: staticItems,
        list: staticItems,
        data: staticItems,
        businesses: staticItems,
        users: staticItems,
        wallets: staticItems,
        transactions: staticItems,
        plans: staticItems,
        agents: staticItems,
        disputes: staticItems,
        refunds: staticItems,
        payouts: staticItems,
        requests: staticItems,
        banners: staticItems,
        downloads: staticItems,
        assets: staticItems,
        invoices: staticItems,
        checkouts: staticItems,
        fundingLinks: staticItems,
        currencies: staticItems,
        countries: staticItems,
        meta: { pageNo: 1, pageSize: 10, total: 3 },
      },
      items: staticItems,
      list: staticItems,
      count: 2,
      total: 2,
      businesses: staticItems,
      users: staticItems,
      wallets: staticItems,
      transactions: staticItems,
      plans: staticItems,
      agents: staticItems,
      disputes: staticItems,
      refunds: staticItems,
      payouts: staticItems,
      requests: staticItems,
      banners: staticItems,
      downloads: staticItems,
      assets: staticItems,
      invoices: staticItems,
      checkouts: staticItems,
      fundingLinks: staticItems,
      currencies: staticItems,
      countries: staticItems,
      meta: { pageNo: 1, pageSize: 10, total: 3 },
      user: { _id: 'static', name: 'Static Admin', email: 'admin@finance.com' },
    },
  ]
})
